^https:\/\/api2\.cursor\.sh\/auth\/full_stripe_profile url script-response-body https://raw.githubusercontent.com/magiceses/shadowquanx/master/quanx/rewrite/cursor/cursor.js
^https:\/\/cursor\.com\/api\/dashboard\/get-current-billing-cycle url script-response-body https://raw.githubusercontent.com/magiceses/shadowquanx/master/quanx/rewrite/cursor/cursor_billing.js
^https:\/\/cursor\.com\/api\/dashboard\/get-service-account-spend-limit url script-response-body https://raw.githubusercontent.com/magiceses/shadowquanx/master/quanx/rewrite/cursor/cursor_account.js
^https:\/\/cursor\.com\/auth\/stripe url script-response-body https://raw.githubusercontent.com/magiceses/shadowquanx/master/quanx/rewrite/cursor/cursor_stripe.js

[mitm]
hostname=api2.cursor.sh, cursor.com
