^https:\/\/www\.macv\.com\/api\/user_management_top url script-response-body https://raw.githubusercontent.com/magiceses/shadowquanx/master/quanx/rewrite/macv/macv.js
^https:\/\/www\.macv\.com\/api\/download url script-response-body https://raw.githubusercontent.com/magiceses/shadowquanx/master/quanx/rewrite/macv/macv_2.js

hostname = www.macv.com
